[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "rm -rf dist server-dist",
  "vite build",
  "esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outfile=server-dist/index.mjs"
]

[start]
cmd = "NODE_ENV=production node server-dist/index.mjs"
